#pragma once

#include "biscuit/isa.hpp"
#include "biscuit/registers.hpp"
#include "felix86/backend/allocation_map.hpp"
#include "felix86/backend/instruction.hpp"

struct Backend;

struct Emitter {
    static void Emit(Backend& backend, const AllocationMap& allocations, const BackendInstruction& instruction);
    static void EmitJump(Backend& backend, void* target);
    static void EmitJumpConditional(Backend& backend, biscuit::GPR condition, void* target_true, void* target_false);
    static void EmitSetExitReason(Backend&, u64);

private:
    static void EmitMov(Backend&, biscuit::GPR, biscuit::GPR);
    static void EmitMov(Backend&, biscuit::FPR, biscuit::FPR);
    static void EmitMov(Backend&, biscuit::Vec, biscuit::Vec);
    static void EmitStoreSpill(Backend&, biscuit::GPR, u32);
    static void EmitStoreSpill(Backend&, biscuit::FPR, u32);
    static void EmitStoreSpill(Backend&, biscuit::Vec, u32);
    static void EmitLoadSpill(Backend&, biscuit::GPR, u32);
    static void EmitLoadSpill(Backend&, biscuit::FPR, u32);
    static void EmitLoadSpill(Backend&, biscuit::Vec, u32);
    static void EmitImmediate(Backend&, biscuit::GPR, u64);
    static void EmitRdtsc(Backend&);
    static void EmitSyscall(Backend&);
    static void EmitCpuid(Backend&);
    static void EmitSext8(Backend&, biscuit::GPR, biscuit::GPR);
    static void EmitSext16(Backend&, biscuit::GPR, biscuit::GPR);
    static void EmitSext32(Backend&, biscuit::GPR, biscuit::GPR);
    static void EmitZext8(Backend&, biscuit::GPR, biscuit::GPR);
    static void EmitZext16(Backend&, biscuit::GPR, biscuit::GPR);
    static void EmitZext32(Backend&, biscuit::GPR, biscuit::GPR);
    static void EmitClz(Backend&, biscuit::GPR, biscuit::GPR);
    static void EmitCtzh(Backend&, biscuit::GPR, biscuit::GPR);
    static void EmitCtzw(Backend&, biscuit::GPR, biscuit::GPR);
    static void EmitCtz(Backend&, biscuit::GPR, biscuit::GPR);
    static void EmitNot(Backend&, biscuit::GPR, biscuit::GPR);
    static void EmitNeg(Backend&, biscuit::GPR, biscuit::GPR);
    static void EmitParity(Backend&, biscuit::GPR, biscuit::GPR);
    static void EmitDiv128(Backend&, biscuit::GPR);
    static void EmitDivu128(Backend&, biscuit::GPR);
    static void EmitReadByte(Backend&, biscuit::GPR, biscuit::GPR);
    static void EmitReadWord(Backend&, biscuit::GPR, biscuit::GPR);
    static void EmitReadDWord(Backend&, biscuit::GPR, biscuit::GPR);
    static void EmitReadQWord(Backend&, biscuit::GPR, biscuit::GPR);
    static void EmitReadXmmWord(Backend&, biscuit::Vec, biscuit::GPR);
    static void EmitReadByteRelative(Backend&, biscuit::GPR, biscuit::GPR, u64);
    static void EmitReadQWordRelative(Backend&, biscuit::GPR, biscuit::GPR, u64);
    static void EmitWriteByte(Backend&, biscuit::GPR, biscuit::GPR);
    static void EmitWriteWord(Backend&, biscuit::GPR, biscuit::GPR);
    static void EmitWriteDWord(Backend&, biscuit::GPR, biscuit::GPR);
    static void EmitWriteQWord(Backend&, biscuit::GPR, biscuit::GPR);
    static void EmitWriteXmmWord(Backend&, biscuit::GPR, biscuit::Vec);
    static void EmitWriteByteRelative(Backend&, biscuit::GPR, biscuit::GPR, u64);
    static void EmitWriteQWordRelative(Backend&, biscuit::GPR, biscuit::GPR, u64);
    static void EmitAdd(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR);
    static void EmitAddi(Backend&, biscuit::GPR, biscuit::GPR, u64);
    static void EmitAmoAdd8(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR, biscuit::Ordering);
    static void EmitAmoAdd16(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR, biscuit::Ordering);
    static void EmitAmoAdd32(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR, biscuit::Ordering);
    static void EmitAmoAdd64(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR, biscuit::Ordering);
    static void EmitAmoAnd8(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR, biscuit::Ordering);
    static void EmitAmoAnd16(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR, biscuit::Ordering);
    static void EmitAmoAnd32(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR, biscuit::Ordering);
    static void EmitAmoAnd64(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR, biscuit::Ordering);
    static void EmitAmoOr8(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR, biscuit::Ordering);
    static void EmitAmoOr16(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR, biscuit::Ordering);
    static void EmitAmoOr32(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR, biscuit::Ordering);
    static void EmitAmoOr64(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR, biscuit::Ordering);
    static void EmitAmoXor8(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR, biscuit::Ordering);
    static void EmitAmoXor16(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR, biscuit::Ordering);
    static void EmitAmoXor32(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR, biscuit::Ordering);
    static void EmitAmoXor64(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR, biscuit::Ordering);
    static void EmitAmoSwap8(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR, biscuit::Ordering);
    static void EmitAmoSwap16(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR, biscuit::Ordering);
    static void EmitAmoSwap32(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR, biscuit::Ordering);
    static void EmitAmoSwap64(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR, biscuit::Ordering);
    static void EmitAmoCAS8(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR, biscuit::GPR, biscuit::Ordering);
    static void EmitAmoCAS16(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR, biscuit::GPR, biscuit::Ordering);
    static void EmitAmoCAS32(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR, biscuit::GPR, biscuit::Ordering);
    static void EmitAmoCAS64(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR, biscuit::GPR, biscuit::Ordering);
    static void EmitSub(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR);
    static void EmitAnd(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR);
    static void EmitOr(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR);
    static void EmitXor(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR);
    static void EmitEqual(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR);
    static void EmitNotEqual(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR);
    static void EmitSetLessThanSigned(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR);
    static void EmitSetLessThanUnsigned(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR);
    static void EmitShiftLeft(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR);
    static void EmitShiftRight(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR);
    static void EmitShiftRightArithmetic(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR);
    static void EmitLeftRotate8(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR);
    static void EmitLeftRotate16(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR);
    static void EmitLeftRotate32(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR);
    static void EmitLeftRotate64(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR);
    static void EmitDiv(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR);
    static void EmitDivu(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR);
    static void EmitDivw(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR);
    static void EmitDivuw(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR);
    static void EmitRem(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR);
    static void EmitRemu(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR);
    static void EmitRemw(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR);
    static void EmitRemuw(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR);
    static void EmitMul(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR);
    static void EmitMulh(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR);
    static void EmitMulhu(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR);
    static void EmitSelect(Backend&, biscuit::GPR, biscuit::GPR, biscuit::GPR, biscuit::GPR);
    static void EmitCastVectorFromInteger(Backend&, biscuit::Vec, biscuit::GPR);
    static void EmitCastIntegerFromVector(Backend&, biscuit::GPR, biscuit::Vec);
    static void EmitVInsertInteger(Backend&, biscuit::Vec, biscuit::GPR, biscuit::Vec, u64);
    static void EmitVExtractInteger(Backend&, biscuit::GPR, biscuit::Vec, u64);
    static void EmitVPackedShuffleDWord(Backend&, biscuit::Vec, biscuit::Vec, u64);
    static void EmitVMoveByteMask(Backend&, biscuit::Vec, biscuit::Vec);
    static void EmitVUnpackByteLow(Backend&, biscuit::Vec, biscuit::Vec, biscuit::Vec);
    static void EmitVUnpackWordLow(Backend&, biscuit::Vec, biscuit::Vec, biscuit::Vec);
    static void EmitVUnpackDWordLow(Backend&, biscuit::Vec, biscuit::Vec, biscuit::Vec);
    static void EmitVUnpackQWordLow(Backend&, biscuit::Vec, biscuit::Vec, biscuit::Vec);
    static void EmitVAnd(Backend&, biscuit::Vec, biscuit::Vec, biscuit::Vec);
    static void EmitVOr(Backend&, biscuit::Vec, biscuit::Vec, biscuit::Vec);
    static void EmitVXor(Backend&, biscuit::Vec, biscuit::Vec, biscuit::Vec);
    static void EmitVShiftRight(Backend&, biscuit::Vec, biscuit::Vec, biscuit::Vec);
    static void EmitVShiftLeft(Backend&, biscuit::Vec, biscuit::Vec, biscuit::Vec);
    static void EmitVPackedSubByte(Backend&, biscuit::Vec, biscuit::Vec, biscuit::Vec);
    static void EmitVPackedAddQWord(Backend&, biscuit::Vec, biscuit::Vec, biscuit::Vec);
    static void EmitVPackedEqualByte(Backend&, biscuit::Vec, biscuit::Vec, biscuit::Vec);
    static void EmitVPackedEqualWord(Backend&, biscuit::Vec, biscuit::Vec, biscuit::Vec);
    static void EmitVPackedEqualDWord(Backend&, biscuit::Vec, biscuit::Vec, biscuit::Vec);
    static void EmitVPackedMinByte(Backend&, biscuit::Vec, biscuit::Vec, biscuit::Vec);
    static void EmitVZext64(Backend&, biscuit::Vec, biscuit::Vec);
};