#include "felix86/ir/emitter.h"
#include "felix86/common/log.h"

void __attribute__((weak)) ir_handle_add_rm8_r8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "add_rm8_r8"); }
void __attribute__((weak)) ir_handle_add_rm32_r32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "add_rm32_r32"); }
void __attribute__((weak)) ir_handle_add_r8_rm8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "add_r8_rm8"); }
void __attribute__((weak)) ir_handle_add_r32_rm32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "add_r32_rm32"); }
void __attribute__((weak)) ir_handle_add_al_imm8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "add_al_imm8"); }
void __attribute__((weak)) ir_handle_add_eax_imm32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "add_eax_imm32"); }
void __attribute__((weak)) ir_handle_or_rm8_r8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "or_rm8_r8"); }
void __attribute__((weak)) ir_handle_or_rm32_r32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "or_rm32_r32"); }
void __attribute__((weak)) ir_handle_or_r8_rm8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "or_r8_rm8"); }
void __attribute__((weak)) ir_handle_or_r32_rm32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "or_r32_rm32"); }
void __attribute__((weak)) ir_handle_or_al_imm8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "or_al_imm8"); }
void __attribute__((weak)) ir_handle_or_eax_imm32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "or_eax_imm32"); }
void __attribute__((weak)) ir_handle_secondary_table(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "secondary_table"); }
void __attribute__((weak)) ir_handle_adc_rm8_r8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "adc_rm8_r8"); }
void __attribute__((weak)) ir_handle_adc_rm32_r32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "adc_rm32_r32"); }
void __attribute__((weak)) ir_handle_adc_r8_rm8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "adc_r8_rm8"); }
void __attribute__((weak)) ir_handle_adc_r32_rm32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "adc_r32_rm32"); }
void __attribute__((weak)) ir_handle_adc_al_imm8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "adc_al_imm8"); }
void __attribute__((weak)) ir_handle_adc_eax_imm32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "adc_eax_imm32"); }
void __attribute__((weak)) ir_handle_sbb_rm8_r8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "sbb_rm8_r8"); }
void __attribute__((weak)) ir_handle_sbb_rm32_r32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "sbb_rm32_r32"); }
void __attribute__((weak)) ir_handle_sbb_r8_rm8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "sbb_r8_rm8"); }
void __attribute__((weak)) ir_handle_sbb_r32_rm32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "sbb_r32_rm32"); }
void __attribute__((weak)) ir_handle_sbb_al_imm8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "sbb_al_imm8"); }
void __attribute__((weak)) ir_handle_sbb_eax_imm32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "sbb_eax_imm32"); }
void __attribute__((weak)) ir_handle_and_rm8_r8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "and_rm8_r8"); }
void __attribute__((weak)) ir_handle_and_rm32_r32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "and_rm32_r32"); }
void __attribute__((weak)) ir_handle_and_r8_rm8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "and_r8_rm8"); }
void __attribute__((weak)) ir_handle_and_r32_rm32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "and_r32_rm32"); }
void __attribute__((weak)) ir_handle_and_al_imm8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "and_al_imm8"); }
void __attribute__((weak)) ir_handle_and_eax_imm32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "and_eax_imm32"); }
void __attribute__((weak)) ir_handle_sub_rm8_r8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "sub_rm8_r8"); }
void __attribute__((weak)) ir_handle_sub_rm32_r32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "sub_rm32_r32"); }
void __attribute__((weak)) ir_handle_sub_r8_rm8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "sub_r8_rm8"); }
void __attribute__((weak)) ir_handle_sub_r32_rm32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "sub_r32_rm32"); }
void __attribute__((weak)) ir_handle_sub_al_imm8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "sub_al_imm8"); }
void __attribute__((weak)) ir_handle_sub_eax_imm32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "sub_eax_imm32"); }
void __attribute__((weak)) ir_handle_xor_rm8_r8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "xor_rm8_r8"); }
void __attribute__((weak)) ir_handle_xor_rm32_r32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "xor_rm32_r32"); }
void __attribute__((weak)) ir_handle_xor_r8_rm8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "xor_r8_rm8"); }
void __attribute__((weak)) ir_handle_xor_r32_rm32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "xor_r32_rm32"); }
void __attribute__((weak)) ir_handle_xor_al_imm8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "xor_al_imm8"); }
void __attribute__((weak)) ir_handle_xor_eax_imm32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "xor_eax_imm32"); }
void __attribute__((weak)) ir_handle_cmp_rm8_r8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "cmp_rm8_r8"); }
void __attribute__((weak)) ir_handle_cmp_rm32_r32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "cmp_rm32_r32"); }
void __attribute__((weak)) ir_handle_cmp_r8_rm8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "cmp_r8_rm8"); }
void __attribute__((weak)) ir_handle_cmp_r32_rm32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "cmp_r32_rm32"); }
void __attribute__((weak)) ir_handle_cmp_al_imm8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "cmp_al_imm8"); }
void __attribute__((weak)) ir_handle_cmp_eax_imm32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "cmp_eax_imm32"); }
void __attribute__((weak)) ir_handle_push_r32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "push_r32"); }
void __attribute__((weak)) ir_handle_pop_r32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "pop_r32"); }
void __attribute__((weak)) ir_handle_movsxd(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "movsxd"); }
void __attribute__((weak)) ir_handle_push_imm32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "push_imm32"); }
void __attribute__((weak)) ir_handle_imul_r32_rm32_imm32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "imul_r32_rm32_imm32"); }
void __attribute__((weak)) ir_handle_push_imm8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "push_imm8"); }
void __attribute__((weak)) ir_handle_imul_r32_rm32_imm8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "imul_r32_rm32_imm8"); }
void __attribute__((weak)) ir_handle_jo_rel8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "jo_rel8"); }
void __attribute__((weak)) ir_handle_jno_rel8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "jno_rel8"); }
void __attribute__((weak)) ir_handle_jc_rel8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "jc_rel8"); }
void __attribute__((weak)) ir_handle_jnc_rel8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "jnc_rel8"); }
void __attribute__((weak)) ir_handle_jz_rel8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "jz_rel8"); }
void __attribute__((weak)) ir_handle_jnz_rel8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "jnz_rel8"); }
void __attribute__((weak)) ir_handle_jbe_rel8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "jbe_rel8"); }
void __attribute__((weak)) ir_handle_ja_rel8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "ja_rel8"); }
void __attribute__((weak)) ir_handle_js_rel8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "js_rel8"); }
void __attribute__((weak)) ir_handle_jns_rel8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "jns_rel8"); }
void __attribute__((weak)) ir_handle_jp_rel8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "jp_rel8"); }
void __attribute__((weak)) ir_handle_jnp_rel8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "jnp_rel8"); }
void __attribute__((weak)) ir_handle_jl_rel8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "jl_rel8"); }
void __attribute__((weak)) ir_handle_jge_rel8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "jge_rel8"); }
void __attribute__((weak)) ir_handle_jle_rel8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "jle_rel8"); }
void __attribute__((weak)) ir_handle_jg_rel8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "jg_rel8"); }
void __attribute__((weak)) ir_handle_group1_rm8_imm8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "group1_rm8_imm8"); }
void __attribute__((weak)) ir_handle_group1_rm32_imm32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "group1_rm32_imm32"); }
void __attribute__((weak)) ir_handle_group1_rm32_imm8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "group1_rm32_imm8"); }
void __attribute__((weak)) ir_handle_test_rm8_r8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "test_rm8_r8"); }
void __attribute__((weak)) ir_handle_test_rm32_r32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "test_rm32_r32"); }
void __attribute__((weak)) ir_handle_xchg_rm8_r8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "xchg_rm8_r8"); }
void __attribute__((weak)) ir_handle_xchg_rm32_r32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "xchg_rm32_r32"); }
void __attribute__((weak)) ir_handle_mov_rm8_r8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "mov_rm8_r8"); }
void __attribute__((weak)) ir_handle_mov_rm32_r32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "mov_rm32_r32"); }
void __attribute__((weak)) ir_handle_mov_r8_rm8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "mov_r8_rm8"); }
void __attribute__((weak)) ir_handle_mov_r32_rm32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "mov_r32_rm32"); }
void __attribute__((weak)) ir_handle_mov_from_sreg(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "mov_from_sreg"); }
void __attribute__((weak)) ir_handle_lea(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "lea"); }
void __attribute__((weak)) ir_handle_mov_to_sreg(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "mov_to_sreg"); }
void __attribute__((weak)) ir_handle_pop_rm32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "pop_rm32"); }
void __attribute__((weak)) ir_handle_xchg_reg(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "ir_handle_xchg_reg"); }
void __attribute__((weak)) ir_handle_cwde(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "cwde"); }
void __attribute__((weak)) ir_handle_cdq(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "cdq"); }
void __attribute__((weak)) ir_handle_push_flags(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "push_flags"); }
void __attribute__((weak)) ir_handle_pop_flags(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "pop_flags"); }
void __attribute__((weak)) ir_handle_sahf(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "sahf"); }
void __attribute__((weak)) ir_handle_lahf(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "lahf"); }
void __attribute__((weak)) ir_handle_mov_al_moffs8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "mov_al_moffs8"); }
void __attribute__((weak)) ir_handle_mov_eax_moffs32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "mov_eax_moffs32"); }
void __attribute__((weak)) ir_handle_mov_moffs8_al(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "mov_moffs8_al"); }
void __attribute__((weak)) ir_handle_mov_moffs32_eax(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "mov_moffs32_eax"); }
void __attribute__((weak)) ir_handle_movsb(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "movsb"); }
void __attribute__((weak)) ir_handle_movsd(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "movsd"); }
void __attribute__((weak)) ir_handle_cmpsb(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "cmpsb"); }
void __attribute__((weak)) ir_handle_cmpsd(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "cmpsd"); }
void __attribute__((weak)) ir_handle_test_al_imm8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "test_al_imm8"); }
void __attribute__((weak)) ir_handle_test_eax_imm32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "test_eax_imm32"); }
void __attribute__((weak)) ir_handle_stosb(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "stosb"); }
void __attribute__((weak)) ir_handle_stosd(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "stosd"); }
void __attribute__((weak)) ir_handle_lodsb(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "lodsb"); }
void __attribute__((weak)) ir_handle_lodsd(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "lodsd"); }
void __attribute__((weak)) ir_handle_scasb(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "scasb"); }
void __attribute__((weak)) ir_handle_scasd(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "scasd"); }
void __attribute__((weak)) ir_handle_mov_r8_imm8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "mov_r8_imm8"); }
void __attribute__((weak)) ir_handle_mov_r32_imm32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "mov_r32_imm32"); }
void __attribute__((weak)) ir_handle_group2_rm8_imm8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "group2_rm8_imm8"); }
void __attribute__((weak)) ir_handle_group2_rm32_imm8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "group2_rm32_imm8"); }
void __attribute__((weak)) ir_handle_ret_imm16(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "ret_imm16"); }
void __attribute__((weak)) ir_handle_ret(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "ret"); }
void __attribute__((weak)) ir_handle_mov_rm8_imm8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "mov_rm8_imm8"); }
void __attribute__((weak)) ir_handle_mov_rm32_imm32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "mov_rm32_imm32"); }
void __attribute__((weak)) ir_handle_enter(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "enter"); }
void __attribute__((weak)) ir_handle_leave(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "leave"); }
void __attribute__((weak)) ir_handle_group2_rm8_1(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "group2_rm8_1"); }
void __attribute__((weak)) ir_handle_group2_rm32_1(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "group2_rm32_1"); }
void __attribute__((weak)) ir_handle_group2_rm8_cl(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "group2_rm8_cl"); }
void __attribute__((weak)) ir_handle_group2_rm32_cl(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "group2_rm32_cl"); }
void __attribute__((weak)) ir_handle_loopnz_rel8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "loopnz_rel8"); }
void __attribute__((weak)) ir_handle_loopz_rel8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "loopz_rel8"); }
void __attribute__((weak)) ir_handle_loop_rel8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "loop_rel8"); }
void __attribute__((weak)) ir_handle_jecxz_rel8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "jecxz_rel8"); }
void __attribute__((weak)) ir_handle_call_rel32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "call_rel32"); }
void __attribute__((weak)) ir_handle_jmp_rel32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "jmp_rel32"); }
void __attribute__((weak)) ir_handle_jmp_rel8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "jmp_rel8"); }
void __attribute__((weak)) ir_handle_hlt(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "hlt"); }
void __attribute__((weak)) ir_handle_group3_rm8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "group3_rm8"); }
void __attribute__((weak)) ir_handle_group3_rm32(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "group3_rm32"); }
void __attribute__((weak)) ir_handle_clc(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "clc"); }
void __attribute__((weak)) ir_handle_stc(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "stc"); }
void __attribute__((weak)) ir_handle_cld(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "cld"); }
void __attribute__((weak)) ir_handle_std(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "std"); }
void __attribute__((weak)) ir_handle_inc_dec_rm8(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "inc_dec_rm8"); }
void __attribute__((weak)) ir_handle_group4(ir_emitter_state_t* state, x86_instruction_t* inst) { ERROR("STUB: Unimplemented ir handler: %s", "group4"); }
